### ISSUE TITLE
Add support of blob: resources

### ISSUE THREAD

**Issue by AlttiRi** [brian-girko/save-as-mhtml#13]
`blob:` resources are not allowed to load in mhtml. 

When you try to open such file: you will get the error `Not allowed to load local resource: blob:https://mega.nz/4231854e-4ae5-45cf-a299-28185332ce12` in the browser console.

![Screenshot](https://user-images.githubusercontent.com/16310547/105316290-b8b38f80-5bd1-11eb-966a-5fba759689aa.png)

_[1]_
The easier fix for it is just modify all URLs by removing `blob:` part.
```js
mhtml.replaceAll("blob:", "");
```

But it does not work for such case:
```
8f-aa31-8ea0e2b3e0c8"><link type=3D"text/css" rel=3D"stylesheet" href=3D"bl=
ob:https://mega.nz/e232d54a-04fa-421f-a4e6-0545601f22dc"><meta name=3D"robo=
```
_Note: MHTML uses `\r\n`, not `\n`._

_[2]_
A bit more correct way to fix it is
```js
mhtml.replaceAll(/b(=\r\n)?l(=\r\n)?o(=\r\n)?b(=\r\n)?:(=\r\n)?/g, "");
````

But if the site contain the text `blob:` _**(a visible text, not in html)**_ it will be removed too.

**_[3]_**
Not ideal, but the more correct way is to also check the site protocol + host:
```js
const site = location.protocol + "//" + location.host;
const regexString = [..."blob:", ""].join("(=\\r\\n)?") + "(?=" + [...site, ""].join("(=\\r\\n)?") + ")";
const regex = new RegExp(regexString , "g");
const result = mhtml.replaceAll(regex, "");
```

It will replace `blob:` from the page's text too, but only if the domain is the same.

---

The site examples:
https://mega.nz/folder/e1ogxQ7T#ee4Q_ocD1bSLmNeg9B6kBw
https://mega.nz/file/bkwkHC7D#AWJuto8_fhleAI2WG0RvACtKkL_s9tAtvBXXDUp2bQk

Here is the more useful example of the site that I have found in Internet for testing of this case: 
https://mega.nz/folder/D0dXTQzT#eKQhFJCkUXyuMWICezDunw

**Comment by AlttiRi** [comment]
Before:
[[mega.nz] 2021.01.21—MEGA.mhtml.zip](https://github.com/brian-girko/save-as-mhtml/files/5847833/mega.nz.2021.01.21.MEGA.mhtml.zip)

After:
[[mega.nz] 2021.01.21—MEGA [edited].mhtml.zip](https://github.com/brian-girko/save-as-mhtml/files/5847831/mega.nz.2021.01.21.MEGA.edited.mhtml.zip)


_I just edited it with NotePad++ by using this regex:_
`b(=\r\n)?l(=\r\n)?o(=\r\n)?b(=\r\n)?:(=\r\n)?(?=h(=\r\n)?t(=\r\n)?t(=\r\n)?p(=\r\n)?s(=\r\n)?:(=\r\n)?/(=\r\n)?/(=\r\n)?m(=\r\n)?e(=\r\n)?g(=\r\n)?a(=\r\n)?.(=\r\n)?n(=\r\n)?z(=\r\n)?)`

**Comment by AlttiRi** [comment]
I think this should be implemented as an option "blob: workaround" (enabled by default, currently).
Most likely, it's Chromium's bug. And theoretically it may be fixed in the future. _(or not)_

**Comment by AlttiRi** [comment]
Probably the better way is to check the existence of `Content-Location: ` or `3D"` (`3(=\r\n)?D(=\r\n)?"(=\r\n)?`) before `blob:` text.
It should work in 99+ % of cases when the page contains the "blob:" text.

Currently the extension may break the content.

**Comment by AlttiRi** [comment]
For example: https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used

Currently:
The original page
![1](https://user-images.githubusercontent.com/16310547/105635847-4c0cef00-5e76-11eb-8462-e327037b7854.png)

MHTML
![2](https://user-images.githubusercontent.com/16310547/105635852-56c78400-5e76-11eb-8816-2b97e2982cfa.png)

**Comment by AlttiRi** [comment]
Here is it:
`/(?<=(Content-Location: )|(3D")|(3=\r\nD")|(3D=\r\n")|(3D"=\r\n))b(=\r\n)?l(=\r\n)?o(=\r\n)?b(=\r\n)?:(=\r\n)?/`
```js
const regexString = `(?<=(Content-Location: )|3D"|3=\\r\\nD"|3D=\\r\\n"|3D"=\\r\\n)` + [..."blob:", ""].join("(=\\r\\n)?");
const regex = new RegExp(regexString, "g");
```

It finds all `blob:` before which there is `Content-Location: `, or `3D"`, or `3=\r\nD"`, or `3D=\r\n"`, or `3D"=\r\n`.


_Damn, Notepad++ does not support regex with alternatives with different length inside lookbehind. Just remove `?<=` for testing._

**Comment by AlttiRi** [comment]
By the way, your code
https://github.com/brian-girko/save-as-mhtml/blob/d0223c3c796bfa2b7e34155682db0f6f69ddd0b3/chrome/background.js#L27
does not works well.
It does not match this case:
```
</span><span class=3D"block-view-file-type pdf file"><img src=3D"blob:https=
://mega.nz/09d1b00c-1fc2-4091-8432-0e6a2bebd4e6"></span><span class=3D"file=
```
Here is the correct implementation of the thing, that you wanted to do:
```js
const url = new URL(tab.url);
const sitePrefix = url.protocol + "//";   // "https://"
const blobPrefix = "blob:" + sitePrefix;  // "blob:https://"
const regexString = [...blobPrefix, ""].join("(=\\r\\n)?");
```

With counting of that I talked about in my previous message:
```js
const url = new URL(tab.url);
const sitePrefix = url.protocol + "//";   // "https://"
const blobPrefix = "blob:" + sitePrefix;  // "blob:https://"
const lookbehind= `(?<=(Content-Location: )|3D"|3=\\r\\nD"|3D=\\r\\n"|3D"=\\r\\n)`;
const regexString = lookbehind + [...blobPrefix, ""].join("(=\\r\\n)?");

const regex = new RegExp(regexString, "g");
```

**Comment by brian-girko** [comment]
Since the blob URL in front of the `Content-Location` is not wrapped, why not have sometime simple like:

```js
    // remove blob references
    if (prefs.blob) {
      content.replace(/Content-Location: (blob:https?:\/\/[^\s]+)/g, (a, href) => {
        const r = new RegExp(href.split('').join('(=\\r\\n)?'), 'g');
        content = content.replace(r, href.replace('blob:', 'cid:blob.'));
      });
    }
```

**Comment by AlttiRi** [comment]
Looks not bad.

~Not sure, does it care about cases when the same blob URL is used twice or more times?~
UPD. Checked: it works in this case.

<details>
<summary>The old text</summary>

You can use this code snipped

```js
[...document.querySelectorAll(".thumb img")].forEach(img => img.src = document.querySelector("#v1c1yS6S > .thumb img").src)
```
for this page: https://mega.nz/folder/D0dXTQzT#eKQhFJCkUXyuMWICezDunw

to set the same URL for all thumbnails for the test purpose.

</details>

_Hm... `content.replace(r, ...` works as `replaceAll`?_

---
_Just a note_ 
_However it still does not count the cases when the mhtml content is presented on a web page as a text.
But these are rather rare cases. The fix from above should be enough._

_For example (try to save this page):_
```
<meta name=3D"apple-itunes-app" content=3D"app-id=3D706857885">
"text/css" rel=3D"stylesheet" href=3D"blob:https://mega.nz/1dbbabcf-27eb-4a=
70-b110-83648d6958c5"><meta name=3D"robots" content=3D"noindex"><meta name=

e"><img src=3D"blob:https://mega.nz/1dbbabcf-27eb-4a70-b110-83648d6958c5"><=
e"><img src=3D"blob:https://mega.nz/1dbbabcf-27eb-4a70-b110-83648d6958c5"><=

------MultipartBoundary--kBhl5hGb8DFK5SufScUy0wBc2FkR5J5nXaMr5a6d7X----
Content-Type: text/css
Content-Transfer-Encoding: quoted-printable
Content-Location: blob:https://mega.nz/1dbbabcf-27eb-4a70-b110-83648d6958c5
```

**Comment by AlttiRi** [comment]
Well, [that](https://github.com/brian-girko/save-as-mhtml/issues/13#issuecomment-766555412) should be enough for almost all of cases.
Btw, check my [this comment](https://github.com/brian-girko/save-as-mhtml/issues/16#issuecomment-766370110) if you have missed it.

**Comment by brian-girko** [comment]
Okay, let have this new method on 0.2.2 release. Also we are going to use `[simplified-hostname]` per your comment.
