### ISSUE TITLE
Display "Save as" dialog by default

### ISSUE THREAD

**Issue by AlttiRi** [brian-girko/save-as-mhtml#14]
As I noted here: https://github.com/brian-girko/save-as-mhtml/issues/12#issuecomment-764179784
Saving in Chrome does not work correctly even with `mht` file extension.
So I think "Display the file-chooser to allow the user to select the file location" option should be enabled by default for Chrome (or for all browsers).

With this option files are saved successfully.

**Comment by brian-girko** [comment]
>  Saving in Chrome does not work correctly even with mht file extension.

I tried on both Windows and Mac. With the new `mht` file extension, I don't see the warning and the file saved just fine.

**Comment by AlttiRi** [comment]
Well, it's strange. Yeah, it works in Windows in a virtual machine fine, but does not work in my main OS's Chrome.
Chromes are the same — 88.0.4324.104.

**Comment by AlttiRi** [comment]
With Chrome 89 now the error shows even in VM's Chrome.

**Comment by brian-girko** [comment]
I just tested on 89 and not able to reproduce. Do you have this issue with the other similar extensions?

**Comment by AlttiRi** [comment]
It's really strange behaviour.
I have checked in the _other VM_ with the same Chrome 89.0.4389.82, and it works.

While in the first one now I get:

![Screenshot](https://user-images.githubusercontent.com/16310547/110816317-4b9cac00-829c-11eb-84b9-bbecb57e7154.png)
![Screenshot_1](https://user-images.githubusercontent.com/16310547/110816324-4ccdd900-829c-11eb-8856-a236bbaa9414.png)

---

https://chrome.google.com/webstore/detail/save-as-mht/hfmodljjaibbdndlikgagimhhodmobkc
It uses the save dialog so it works.

https://chrome.google.com/webstore/detail/save-as-mhtml-mime-html/djbjejcpegcimjdappppobfhaafbmjpf/related
This works as your one. (The warning  also appears in Chrome).

UPD.
In the second VM, where your extension works, this `djbjejcpegcimjdappppobfhaafbmjpf` does not works (Possibly because of it uses ".mhtml").

![Screenshot_2](https://user-images.githubusercontent.com/16310547/110818009-ed70c880-829d-11eb-88df-3b4689f54091.png)

**Comment by AlttiRi** [comment]
I get it.
It shows only if you have selected "No protection" in "Safe Browsing".

![Screenshot](https://user-images.githubusercontent.com/16310547/111480680-4d0a2080-8743-11eb-81ad-40f7d71fed81.png)
With this option I get this warning for downloading of executable files also.
That's a strange behaviour.

It works ok with "Standard protection".

**Comment by brian-girko** [comment]
I see! So I guess the current config works as expected. For those who have changed the standard behavior, we have the option to show the dialog box.
