### ISSUE TITLE
Missed filename if there is `~` in a title

### ISSUE THREAD

**Issue by AlttiRi** [brian-girko/save-as-mhtml#19]
`~` is allowed character for Linux and Windows, but the extension does not work correctly with it. I get `page.html` instead of the proper filename if `document.title` contains `~`.

Run it in console:
```
document.title = "123~123"
```
and try to save the page.

**Comment by AlttiRi** [comment]
I see no reason why it does not work. Probably it's Chromium's bug.

But anyway the browser replaces `~` with `_` when you download a file, so you can just add the same replacement. Tested with `<a download="123~123"></a>` +`a.click()`.

But,  for example, I can save a file with `~` in the name by typing it in "Save as" dialog.

**Comment by brian-girko** [comment]
Thanks for the report. We have it on the exception list.
