### ISSUE TITLE
The problem of saving local static pages

### ISSUE THREAD

**Issue by SlRofa-SUSE** [brian-girko/save-as-mhtml#20]
Hello, I'm trying to convert a local static page to MHTML, which is a html file exported by typora, which contains some local images (I need to convert it to a file for sharing). 
When I open it using EDGE or Chrome, the console displays "Not allowed to load local resource:". 
The image was not loaded correctly, but when I tried to open it in an IE browser, it was displayed correctly. 
It is hoped that the author can fix the problem.

**Comment by brian-girko** [comment]
Hi, You need to use a local server; https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
