### ISSUE TITLE
Save as MHTML "Stuck" as saving as TXT ending even if contents are MHTML.

### ISSUE THREAD

**Issue by Black3ird** [brian-girko/save-as-mhtml#3]
Dear Sir,

I was using another extension of same nature until yours offered smaller file sizes compared to other but lately been thinking to revert to back to the other because your extension manifested a TXT bug that got stuck even after Uninstall Extension > Restart Chrome > Install Extension routine which absolutely didn't help with your extension even if it did RESET all other problematic extensions so far.

What went wrong was; a Text Area was "SELECTED" prior to pressing to your Button (no right click menu actions such as "Save as" or no usage of default Chrome Save). And all of a sudden your extension decided to change the endings of all saved files to *.TXT IRREVERSIBLY even if files are in MHTML format as renaming the file to *.mhtml make them open correctly in Chrome.

So whatever you coded make it stuck that TXT extension is preserved between Uninstall / Restart / Re-Install cycle which indicates that you're using unorthodox methods to save your non-existent preferences to be stuck with TXT ending in "other" files on Chrome Profile other than \AppData\Local\Google\Chrome\User Data\Default\Extensions\ahgakckdonjmnpnegjcamhagackmjpei.

Going to keep your extension for a week to see if it gets updated with a "Fix" and will remove if not to revert back to my previous Save as "Whole Page" extension. Not going to follow up this post as already told what you needed to know and attaching a GIF telling what's going on; 
![2019-10-31_15-21-43](https://user-images.githubusercontent.com/7997566/67946472-80055000-fbf2-11e9-86ab-6a8e5dd1375f.gif)

Thanks for so far and hoping you can come up with a fix...

Best Regards.

**Comment by YangsonHung** [comment]
@Black3ird 
background.js:
```js
'use strict';

chrome.browserAction.onClicked.addListener(tab => chrome.pageCapture.saveAsMHTML({
  tabId: tab.id
}, bin => {
  const blob = new Blob([bin], {
    type: 'plain/mhtml'
  });
  chrome.storage.local.get({
    'notify': true,
    'saveAs': false,
    'filename': '[title]',
    'extension': 'mhtml'
  }, prefs => {
    const lastError = chrome.runtime.lastError;
    if (lastError) {
      return prefs.notify && chrome.notifications.create(null, {
        type: 'basic',
        iconUrl: '/data/icons/48.png',
        title: chrome.runtime.getManifest().name,
        message: lastError.message
      });
    }
    const url = URL.createObjectURL(blob);
    const filename = prefs.filename
      .replace(/\[title\]/g, tab.title)
      .replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>{}[\]\\/]/gi, '-');

    chrome.downloads.download({
      url,
      saveAs: prefs.saveAs,
      filename: filename + '.' + prefs.extension
    }, () => {
      URL.revokeObjectURL(url);
    });
  });
}));

// FAQs and Feedback
{
  const {onInstalled, setUninstallURL, getManifest} = chrome.runtime;
  const {name, version} = getManifest();
  const page = getManifest().homepage_url;
  onInstalled.addListener(({reason, previousVersion}) => {
    chrome.storage.local.get({
      'faqs': true,
      'last-update': 0
    }, prefs => {
      if (reason === 'install' || (prefs.faqs && reason === 'update')) {
        const doUpdate = (Date.now() - prefs['last-update']) / 1000 / 60 / 60 / 24 > 45;
        if (doUpdate && previousVersion !== version) {
          chrome.tabs.create({
            url: page + '?version=' + version +
              (previousVersion ? '&p=' + previousVersion : '') +
              '&type=' + reason,
            active: reason === 'install'
          });
          chrome.storage.local.set({'last-update': Date.now()});
        }
      }
    });
  });
  setUninstallURL(page + '?rd=feedback&name=' + encodeURIComponent(name) + '&version=' + version);
}

```

package:
[Save-as-MHTML_v0.1.4.zip](https://github.com/brian-girko/save-as-mhtml/files/4057715/Save-as-MHTML_v0.1.4.zip)
