### ISSUE TITLE
Local pages are not saved

### ISSUE THREAD

**Issue by 64kramsystem** [brian-girko/save-as-mhtml#4]
(similar/same as https://github.com/vsDizzy/SaveAsMHT/issues/21)

The extension works fine when saving a remote page.

However, when the page is local (file:///...), an error is raised: `Don't have permissions required to capture this page.`

Browser: Chromium 78.0.3904.70, on Ubuntu 18.04.

**Comment by brian-girko** [comment]
If you still cannot save local files, create a local server and open files from "http://127.0.0.1/..." origin.

Use https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb or a desktop alternative to create a local server.

**Comment by brian-girko** [comment]
Also make sure you have checked "allow access to file URLs" on the extensions manager for this extension.
