### ISSUE TITLE
Reading MHTML files

### ISSUE THREAD

**Issue by NotepadPlusUser** [brian-girko/save-as-mhtml#5]
1.  Does your extension allow me to read MHTML files that I have saved?   (I am using Vivaldi.)

2.  If not, what can you recommend to read them?
 * I know that IE reads them, but this browser is about to be executed by Microsoft.
 * There seem to be no reader extensions for Vivaldi or Firefox.
 * I can open them with The Bat! (my email client), but this seems more a workaround.
 * I downloaded Turg's reader, but it is very clumsy, and often fails.

The whole business of saving a webpage is a nightmare.  I do not want to be forced to save a file plus a directory every time I save a page, but no single file solution that keeps the links and pictures seems satisfactory.

**Comment by brian-girko** [comment]
Sorry for the delayed response. You just need to drop the file to the browser. All browsers know how to deal with MHTML files. Alternatively, you can assign your browser to be the default program for MHTML file type.

**Comment by NotepadPlusUser** [comment]
Thanks @brian-girko.  Yes, I have realised that I can save in Vivaldi as MHTML.  But there are further problems.  I saved a few webpages using MHTML — some saved the page correctly, but some did not, and I lost the information.  I use uMatrix to control cookies, and I realised that in some situations — I have no idea which — I can view the webage perfectly OK in Vivaldi, but when I save it, it omit some or all of the page.  Apparently more cookies need to be allowed to save the page in MHTML than to view the page. 

What a mess!  It looks as if PDF is the best solution after all.

**Comment by brian-girko** [comment]
The core API to create an MHTML file is internal to Chrome, so there is no way to alter it. Note that pages that dynamically generate elements cannot be archived very well. Especially pages with iframe elements. I would recommend trying this extension first, and if the result is not satisfying go with the PDF alternative.
