### ISSUE TITLE
Request: include page URL in saved file

### ISSUE THREAD

**Issue by paul1149** [brian-girko/save-as-mhtml#7]
Save as MHTML is working great here.

It would be helpful to me to include a page's original URL to the saved file.

Thanks much.

**Comment by brian-girko** [comment]
I added an experimental metatag section, which is disabled by default. After the next release, you can enable it from the right-click context menu over the toolbar button. Note that this section might mess up the page layout. So give it a try and disable it when not needed.

**Comment by paul1149** [comment]
Thanks much Brian. Sounds great.

**Comment by brian-girko** [comment]
I am closing this. Reopen if needed

**Comment by paul1149** [comment]
Brian, I'm using 0.2.0 in Vivaldi, and I can't get the Add Meta Data  option to do anything. I expect it to work as a check box option, but I don't see any checkbox, nor does the meta data show up in the .mht.

Thanks.

**Comment by brian-girko** [comment]
This is how it looks in Chrome
![Screen Shot 2021-01-24 at 08 02 48](https://user-images.githubusercontent.com/51436935/105631169-fcfa9600-5e44-11eb-8c5f-1ed431951ab8.png)

Note that if a page has a sticky header, the meta might be hidden behind the header. Also note that if you open the "*.mht" file in a text editor you already have the meta part:

```
From: <Saved by Blink>
Snapshot-Content-Location: https://en.wikipedia.org/wiki/Main_Page
Subject: Wikipedia, the free encyclopedia
Date: Sun, 24 Jan 2021 13:03:34 -0000
...
```

**Comment by paul1149** [comment]
Ok, that explains it. There are a few extensions here that work with Vivaldi, but not perfectly. And that tip about the hidden url is very good. That is probably all I need, or I can put the url in the file name.

Thanks again for you time and attention.
Paul
